### ISSUE TITLE
Keep the testing containers up to date by building and pushing using GitHub Actions

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/drupal-container#39]
Would be nice to have a GitHub Action to build and push the containers on a weekly basis.

**Comment by millnut** [comment]
Hi @stephen-cox is this pushing the images to docker hub? If so I was planning to catch up with you to get a better understanding on how this works so we can automated this process

**Comment by chrisns** [comment]
PR #41 adds a GitHub Actions workflow that builds and pushes multi-arch containers to GHCR on every push to `php*` branches.

If you'd like scheduled builds as well, a cron schedule could easily be added to the workflow trigger:

```yaml
on:
  push:
    branches:
      - php*
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight
```

Happy to add this to the PR if that would be useful.
